#pragma once

#define VERTEX_ATTRIBS_LOCATION_POSITION 0
#define VERTEX_ATTRIBS_LOCATION_COLOR 1
#define VERTEX_ATTRIBS_LOCATION_NORMAL 2
#define VERTEX_ATTRIBS_LOCATION_TANGENT 3
#define VERTEX_ATTRIBS_LOCATION_BITANGENT 4
#define VERTEX_ATTRIBS_LOCATION_TEXCOORD0 5
#define VERTEX_ATTRIBS_LOCATION_TEXCOORD1 6
#define VERTEX_ATTRIBS_LOCATION_TEXCOORD2 7
#define VERTEX_ATTRIBS_LOCATION_TEXCOORD3 8
#define VERTEX_ATTRIBS_LOCATION_TEXCOORD4 9
#define VERTEX_ATTRIBS_LOCATION_TEXCOORD5 10
#define VERTEX_ATTRIBS_LOCATION_TEXCOORD6 11
#define VERTEX_ATTRIBS_LOCATION_TEXCOORD7 12

#define INPUT_VERTEX_POSITION(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_POSITION)]] def : POSITION
#define INPUT_VERTEX_NORMAL(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_NORMAL)]] def : NORMAL
#define INPUT_VERTEX_TANGENT(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_TANGENT)]] def : TANGENT
#define INPUT_VERTEX_COLOR(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_COLOR)]] def : COLOR
#define INPUT_VERTEX_TEXCOORD0(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_TEXCOORD0)]] def : TEXCOORD0
#define INPUT_VERTEX_TEXCOORD1(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_TEXCOORD1)]] def : TEXCOORD1
#define INPUT_VERTEX_TEXCOORD2(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_TEXCOORD2)]] def : TEXCOORD2
#define INPUT_VERTEX_TEXCOORD3(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_TEXCOORD3)]] def : TEXCOORD3
#define INPUT_VERTEX_TEXCOORD4(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_TEXCOORD4)]] def : TEXCOORD4
#define INPUT_VERTEX_TEXCOORD5(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_TEXCOORD5)]] def : TEXCOORD5
#define INPUT_VERTEX_TEXCOORD6(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_TEXCOORD6)]] def : TEXCOORD6
#define INPUT_VERTEX_TEXCOORD7(def) [[vk::location(VERTEX_ATTRIBS_LOCATION_TEXCOORD7)]] def : TEXCOORD7
