name = "Cube"

[[components]]
type = "Transform"
[components.value]
translation = [ 0.0, 0.0, 0.0 ]
rotation = [ 0.0, 0.0, 0.0 ]

[[components]]
type = "StaticMeshComponent"
[components.value]
static_mesh = { asset_id = 1 }

[[components]]
type = "MeshRendererComponent"
[components.value]
material = { asset_id = 5 }
