[[assets]]
id = 0
path = '/project/meshes/plane.static_mesh.biasset'
type = 'StaticMesh'

[[assets]]
id = 1
path = '/project/meshes/cube.static_mesh.biasset'
type = 'StaticMesh'

[[assets]]
id = 2
path = '/project/meshes/sphere.static_mesh.biasset'
type = 'StaticMesh'

[[assets]]
id = 3
path = '/project/materials/checkerboard.toml'
type = 'Material'

[[assets]]
id = 4
path = '/project/materials/textured.toml'
type = 'Material'

[[assets]]
id = 5
path = '/project/materials/white.toml'
type = 'Material'

[[assets]]
id = 6
path = '/project/textures/earth_diffuse.texture.biasset'
type = 'Texture'

[[assets]]
id = 7
path = '/project/textures/earth_normal.texture.biasset'
type = 'Texture'

[[assets]]
id = 8
path = '/project/models/cube_prefab.toml'
type = 'Prefab'

[[assets]]
id = 9
path = '/project/materials/transparent.toml'
type = 'Material'

[[assets]]
id = 10
path = '/project/textures/cage.texture.biasset'
type = 'Texture'

[[assets]]
id = 11
path = '/project/materials/cage.toml'
type = 'Material'