name = "Scene Basic"

asset_metadata_file = "/project/asset_metadata.toml"
scene_file = "/project/scene.toml"

renderer = "ForwardRenderer"

[settings.graphics]
backend = "vulkan"
enable_validation = true
