[[objects]]

[[objects.components]]
type = "Transform"
[objects.components.value]
translation = [ 0.0, -1.0, 0.0 ]
scaling = [ 5.0, 1.0, 5.0 ]

[[objects.components]]
type = "StaticMeshComponent"
[objects.components.value]
static_mesh = { asset_path = "/project/models/plane.obj" }

[[objects.components]]
type = "MeshRendererComponent"
[objects.components.value]
material = { asset_path = "/project/materials/checkerboard.toml" }

[[objects]]

[[objects.components]]
type = "Transform"
[objects.components.value]
translation = [ 1.0, 0.0, 1.0 ]
rotation = [ 0.0, 30.0, 0.0 ]

[[objects.components]]
type = "StaticMeshComponent"
[objects.components.value]
static_mesh = { asset_path = "/project/models/cube.obj" }

[[objects.components]]
type = "MeshRendererComponent"
[objects.components.value]
material = { asset_path = "/project/materials/white.toml" }

[[objects]]

[[objects.components]]
type = "Transform"
[objects.components.value]
translation = [ -1.0, 0.0, -1.0 ]

[[objects.components]]
type = "StaticMeshComponent"
[objects.components.value]
static_mesh = { asset_path = "/project/models/sphere.obj" }

[[objects.components]]
type = "MeshRendererComponent"
[objects.components.value]
material = { asset_path = "/project/materials/textured.toml" }

[[objects]]

[[objects.components]]
type = "Transform"
[objects.components.value]
rotation = [ 30.0, 0.0, 10.0 ]

[[objects.components]]
type = "LightComponent"
[objects.components.value]
color = [ 1.0, 0.8, 0.7 ]
strength = 4.0
type = "directional"

[[objects]]

[[objects.components]]
type = "Transform"
[objects.components.value]
translation = [ 7.0, 3.0, 4.0 ]
rotation = [ -36.869898, 54.462322, 0.0 ]

[[objects.components]]
type = "CameraComponent"
value = {}
