[[objects]]
name = "Plane"

[[objects.components]]
type = "Transform"
[objects.components.value]
translation = [ 0.0, -1.0, 0.0 ]
scaling = [ 5.0, 1.0, 5.0 ]

[[objects.components]]
type = "StaticMeshComponent"
[objects.components.value]
static_mesh = { asset_id = 0 }

[[objects.components]]
type = "MeshRendererComponent"
[objects.components.value]
material = { asset_id = 3 }

[[objects]]
name = "Cube"

[[objects.components]]
type = "Transform"
[objects.components.value]
translation = [ 1.0, 0.0, -1.0 ]
rotation = [ 0.0, 30.0, 0.0 ]

[[objects.components]]
type = "StaticMeshComponent"
[objects.components.value]
static_mesh = { asset_id = 1 }

[[objects.components]]
type = "MeshRendererComponent"
[objects.components.value]
material = { asset_id = 5 }

[[objects]]
name = "Sphere"

[[objects.components]]
type = "Transform"
[objects.components.value]
translation = [ -1.0, 0.0, 1.0 ]

[[objects.components]]
type = "StaticMeshComponent"
[objects.components.value]
static_mesh = { asset_id = 2 }

[[objects.components]]
type = "MeshRendererComponent"
[objects.components.value]
material = { asset_id = 4 }

[[objects]]
name = "Dir Light"

[[objects.components]]
type = "Transform"
[objects.components.value]
rotation = [ 10.0, 0.0, -30.0 ]

[[objects.components]]
type = "LightComponent"
[objects.components.value]
color = [ 1.0, 0.9, 0.8 ]
strength = 4.0
type = "directional"

[[objects]]
name = "Camera"

[[objects.components]]
type = "Transform"
[objects.components.value]
translation = [ 10.5, 4.5, 6.0 ]
rotation = [ -9.332409, 63.346549, 17.904466 ]

[[objects.components]]
type = "CameraComponent"
value = {}
