blend_mode = 'opaque'
material_function = '''surface.base_color = base_color_tex.Sample(base_color_tex_sampler, vertex.texcoord0).xyz;
surface.normal_map_value = normal_map.Sample(normal_map_sampler, vertex.texcoord0).xyz;
surface.roughness = roughness;
'''
surface_model = 'lit'

[[params]]
name = 'roughness'
value = 0.20000000298023224

[[params]]
name = 'base_color_tex'

    [params.value]
    asset_id = 6

[[params]]
name = 'normal_map'

    [params.value]
    asset_id = 7