#pragma once

#define BISMUTH_NAMESPACE_BEGIN namespace bismuth {
#define BISMUTH_NAMESPACE_END }

#define BISMUTH_VERSION_MAJOR 0
#define BISMUTH_VERSION_MINOR 1
#define BISMUTH_VERSION_PATCH 0

#define BISMUTH_VULKAN_VERSION_MAJOR 1
#define BISMUTH_VULKAN_VERSION_MINOR 3

#define BISMUTH_D3D12_FEATURE_LEVEL_MAJOR 12
#define BISMUTH_D3D12_FEATURE_LEVEL_MINOR 1
