#pragma once

#define BI_PARENS ()

#define BI_EVAL_MACRO(...) BI_EVAL_MACRO1(BI_EVAL_MACRO1(BI_EVAL_MACRO1(__VA_ARGS__)))
#define BI_EVAL_MACRO1(...) BI_EVAL_MACRO2(BI_EVAL_MACRO2(BI_EVAL_MACRO2(__VA_ARGS__)))
#define BI_EVAL_MACRO2(...) BI_EVAL_MACRO3(BI_EVAL_MACRO3(BI_EVAL_MACRO3(__VA_ARGS__)))
#define BI_EVAL_MACRO3(...) BI_EVAL_MACRO4(BI_EVAL_MACRO4(BI_EVAL_MACRO4(__VA_ARGS__)))
#define BI_EVAL_MACRO4(...) BI_EVAL_MACRO5(BI_EVAL_MACRO5(BI_EVAL_MACRO5(__VA_ARGS__)))
#define BI_EVAL_MACRO5(...) __VA_ARGS__

#define BI_EVAL_MACRO_ONCE(...) __VA_ARGS__
#define BI_EXPAND_ARGS(...) (__VA_ARGS__)
